[package]
name = "pool3_d"
version = "0.1.0"
authors = ["Joachim Behre", "<jhbpuebla@gmail.com>"]
edition = "2021"

[dependencies]

[target.'1.28.2t(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
